[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
new_presale = "CKJKx8AWRdtz4ZPVQhdx5DA8JdJEnrUprEdVVeQLx7nY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./keypair.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
